using System.Collections.Generic;
using HandHero.Core;
using UnityEngine;

// Demo mode (round 5, T4 / D6): a practice arena for recording the game with the
// hands in view, and a warm-up for players. MatchDirector hosts it
// (MatchPhase.Demo: pause, focus loss, wrist button -> MENU); this keeps the
// player invulnerable (hits still flash, sound and slow), keeps one or two slow
// Strikers flying (each comes back by itself after a KO, like any hero), lets
// the ASSIST aim snap to the arena's practice targets (they respawn on their own)
// and hides the Quick Match bot. No timer, no score, no run systems.
// GhostHands and GestureCaptions draw only while IsActive.
// The demo bots are this director's own instances of the run bot prefab, never
// RunDirector's pooled ones, so the demo's slower tuning can't leak into a run.
// Nothing here moves the XR Origin.
public class DemoDirector : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private MatchDirector match;
    [Tooltip("The player's health: invulnerable while the demo is on, full again when it ends")]
    [SerializeField] private HeroHealth playerHealth;
    [Tooltip("Bot prefab generated by the scene builder (the run bot); the demo makes its own instances at scene load")]
    [SerializeField] private RunBot botPrefab;
    [Tooltip("The arena root: demo bots are parented here and use it for their bounds")]
    [SerializeField] private Transform arena;
    [Tooltip("Where the demo bots appear, one each in order; empty = the arena center")]
    [SerializeField] private Transform[] botSpawnPoints;
    [Tooltip("Hidden while the demo is on: the Quick Match bot hero and its ground marker")]
    [SerializeField] private GameObject[] hideDuringDemo;
    [Tooltip("Aim assist targets switched on only in the demo: the arena's practice targets (off in every other mode)")]
    [SerializeField] private AimAssistTarget[] demoAssistTargets;

    [Header("Rules")]
    [Tooltip("Bot count and how much slower and gentler the demo Strikers are than a run's")]
    [SerializeField] private DemoParams rules = DemoParams.Default;
    [Tooltip("Random seed for the demo bots' moves; 0 = different every demo")]
    [SerializeField] private int seed;

    private readonly List<RunBot> _pool = new List<RunBot>(DemoRules.MaxBots);
    private readonly List<BotInputSource> _poolInputs = new List<BotInputSource>(DemoRules.MaxBots);
    private readonly List<RunBot> _bots = new List<RunBot>(DemoRules.MaxBots);
    private MatchStateMachine _subscribedMatch;
    private bool _controlled;

    // The demo is on (MatchPhase.Demo); false again as soon as the match leaves it.
    public bool IsActive { get; private set; }
    public int BotsActive => _bots.Count;

    // After MatchDirector.Awake created the match: leaving MatchPhase.Demo ends the
    // demo in the same call (bots gone, the player mortal again) before any other
    // mode starts.
    private void Start()
    {
        if (match != null && match.Match != null)
        {
            _subscribedMatch = match.Match;
            _subscribedMatch.PhaseChanged += OnMatchPhaseChanged;
        }
        SetAssistTargets(false);
        PrewarmBots();
    }

    private void OnDestroy()
    {
        if (_subscribedMatch != null) _subscribedMatch.PhaseChanged -= OnMatchPhaseChanged;
    }

    private void OnMatchPhaseChanged(MatchPhase phase)
    {
        if (phase == MatchPhase.Demo) Begin();
        else if (IsActive) End();
    }

    // Pause (wrist button, focus loss, headset off): the bots let go and glide, like
    // the run's bots; resumed, they regrab.
    private void Update()
    {
        if (!IsActive) return;
        bool controlled = match == null || !match.IsPaused;
        if (controlled == _controlled) return;
        _controlled = controlled;
        for (int i = 0; i < _bots.Count; i++)
            if (_bots[i] != null) _bots[i].SetControlled(controlled);
    }

    private void Begin()
    {
        if (IsActive || !isActiveAndEnabled) return;
        IsActive = true;
        SetHidden(true);
        SetAssistTargets(true);
        if (playerHealth != null)
        {
            playerHealth.SetInvulnerable(true);
            playerHealth.ResetHealth();
        }
        _controlled = match == null || !match.IsPaused;
        SpawnBots();
    }

    private void End()
    {
        IsActive = false;
        for (int i = 0; i < _bots.Count; i++)
            if (_bots[i] != null) _bots[i].Deactivate();
        _bots.Clear();
        SetAssistTargets(false);
        SetHidden(false);
        if (playerHealth != null)
        {
            playerHealth.SetInvulnerable(false);
            playerHealth.ResetHealth();
        }
    }

    private void SpawnBots()
    {
        PrewarmBots();
        int count = DemoRules.BotCount(rules, _pool.Count);
        if (count == 0) return;

        var seeds = new System.Random(seed != 0 ? seed : System.Environment.TickCount);
        IslandSpec spec = DemoRules.Spec(rules);
        BotArchetype archetype = DemoRules.Archetype(rules);
        float speedScale = DemoRules.SpeedScale(rules);
        Transform enemy = playerHealth != null ? playerHealth.transform : null;

        for (int i = 0; i < count; i++)
        {
            RunBot bot = _pool[i];
            if (bot == null) continue;
            if (_poolInputs[i] != null) _poolInputs[i].SetPace(speedScale);
            bot.Activate(SpawnPoint(i), arena, enemy, spec, BotBrain.SpawnSeed(seeds), _controlled, archetype);
            _bots.Add(bot);
        }
    }

    private Vector3 SpawnPoint(int index)
    {
        if (botSpawnPoints != null && botSpawnPoints.Length > 0)
        {
            Transform point = botSpawnPoints[index % botSpawnPoints.Length];
            if (point != null) return point.position;
        }
        return arena != null ? arena.position : Vector3.zero;
    }

    // Scene load (Start), never mid-demo: MaxBots instances, inactive until Begin.
    private void PrewarmBots()
    {
        if (botPrefab == null || arena == null) return;
        while (_pool.Count < DemoRules.MaxBots)
        {
            RunBot bot = Instantiate(botPrefab, arena.position, Quaternion.identity, arena);
            bot.name = "DemoBot_" + (_pool.Count + 1);
            bot.Deactivate();
            _pool.Add(bot);
            _poolInputs.Add(bot.GetComponent<BotInputSource>());
        }
    }

    private void SetAssistTargets(bool on)
    {
        if (demoAssistTargets == null) return;
        foreach (AimAssistTarget t in demoAssistTargets)
            if (t != null && t.enabled != on) t.enabled = on;
    }

    private void SetHidden(bool hidden)
    {
        if (hideDuringDemo == null) return;
        foreach (GameObject go in hideDuringDemo)
            if (go != null && go.activeSelf == hidden) go.SetActive(!hidden);
    }
}
