using System.Collections.Generic;
using HandHero.Core;
using UnityEngine;
using UnityEngine.InputSystem;

// Runs RUN mode (autonomous plan R8) around RunStateMachine (HandHero.Core):
// spawns the island's bots from a prefab, scales them, counts kills, heals the
// player between islands and handles death / revive. MatchDirector stays the
// host: it owns pause, focus loss and the menu (MatchPhase.Run), so a run and
// a Quick Match can never be on at the same time. Nothing here moves the XR Origin.
public class RunDirector : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private MatchDirector match;
    [SerializeField] private HeroHealth playerHealth;
    [Tooltip("The player hero's run items; bound to the run's inventory while a run is on")]
    [SerializeField] private RunHeroStats playerStats;
    [Tooltip("Bot prefab generated by the scene builder (its own hero, input and controllers)")]
    [SerializeField] private RunBot botPrefab;
    [Tooltip("The arena root: spawned bots are parented here and use it for their bounds")]
    [SerializeField] private Transform arena;
    [Tooltip("Where bots appear, used in turn; empty = the arena center")]
    [SerializeField] private Transform[] botSpawnPoints;
    [Tooltip("Hidden while a run is on: the Quick Match bot hero and its ground marker")]
    [SerializeField] private GameObject[] hideDuringRun;

    [Header("Rules")]
    [SerializeField] private RunParams rules = RunParams.Default;
    [Tooltip("Seconds between a bot going down and the next one appearing (Horde, Arena 3)")]
    [SerializeField] private float respawnInterval = 1.5f;
    [Tooltip("Seconds a downed bot stays before it is removed (its last beam can finish)")]
    [SerializeField] private float corpseTime = 0.3f;
    [Tooltip("Random seed for chests, portals and the shop; 0 = different every run")]
    [SerializeField] private int seed;

    [Header("Run log (D16)")]
    [Tooltip("Append one JSON line per run to <persistentDataPath>/run_log.jsonl at Victory, Defeat or quit (never mid-fight)")]
    [SerializeField] private bool writeRunLog = true;
    [Tooltip("The player's beam: shots, hits, charge shots and pinch holds for the run log")]
    [SerializeField] private PointingBeamController playerAim;
    [SerializeField] private AimModeSetting aimModeSetting;
    [Tooltip("Optional (XR scene only): records VR or TABLE")]
    [SerializeField] private ArenaViewMode viewMode;

    [Header("Debug keys (editor / desktop)")]
    [Tooltip("R = start a run (menu), 1-3 = pick a portal / chest card, B = buy the first affordable shop item, N = leave the shop")]
    [SerializeField] private bool debugKeys = true;

    private RunStateMachine _run;
    private readonly List<RunBot> _bots = new List<RunBot>();
    private float _spawnTimer;
    private int _nextSpawnPoint;

    // Pooled bots (P6, SP-1/SP-4): prewarmed at scene load (round 4, S1: run start
    // used to hitch for 167 ms on device), reused by Activate / Deactivate. A
    // downed bot stays visible for corpseTime, then goes back.
    private ObjectPool<RunBot> _botPool;
    private readonly List<RunBot> _corpses = new List<RunBot>();
    private readonly List<float> _corpseTimers = new List<float>();
    // Per-spawn bot seeds (D9), drawn from the run's own stream.
    private System.Random _spawnSeeds;

    // Run telemetry (P13, D16).
    private readonly RunRecorder _recorder = new RunRecorder();
    private int _rngSeed;

    public RunStateMachine Run => _run;
    public bool IsRunning => _run != null && _run.Phase != RunPhase.Idle;
    public int BotsAlive => _bots.Count;
    // VICTORY / DEFEAT showing; the run waits for MENU.
    public bool IsOver => _run != null && (_run.Phase == RunPhase.Victory || _run.Phase == RunPhase.Defeat);
    public HeroHealth PlayerHealth => playerHealth;

    private void Awake()
    {
        _rngSeed = seed != 0 ? seed : System.Environment.TickCount;
        _run = new RunStateMachine(rules, new System.Random(_rngSeed));
        _run.PhaseChanged += OnRunPhaseChanged;
    }

    private void OnEnable()
    {
        if (playerHealth == null) return;
        playerHealth.Died += OnPlayerDied;
        playerHealth.Damaged += OnPlayerDamaged;
    }

    private void OnDisable()
    {
        if (playerHealth == null) return;
        playerHealth.Died -= OnPlayerDied;
        playerHealth.Damaged -= OnPlayerDamaged;
    }

    // After MatchDirector.Awake created the match (BR-9): leaving MatchPhase.Run
    // ends the run in the same call, not one Update later with items still bound.
    private MatchStateMachine _subscribedMatch;

    private void Start()
    {
        if (match != null && match.Match != null)
        {
            _subscribedMatch = match.Match;
            _subscribedMatch.PhaseChanged += OnMatchPhaseChanged;
        }
        PrewarmBots();
    }

    private void OnDestroy()
    {
        if (_subscribedMatch != null) _subscribedMatch.PhaseChanged -= OnMatchPhaseChanged;
    }

    private void OnMatchPhaseChanged(MatchPhase phase)
    {
        if (phase != MatchPhase.Run && IsRunning) EndRun();
    }

    // Debug key entry point: straight into a run, no tutorial. Only from the main
    // menu. The RUN button goes through MatchDirector (tutorial first) instead;
    // Update begins the run once the match is in MatchPhase.Run.
    public bool StartRun()
    {
        if (IsRunning || match == null || !match.StartRun()) return false;
        BeginRun();
        return true;
    }

    private void BeginRun()
    {
        _run.Params = rules;
        // Before StartRun: it enters island 1's intro, which the recorder logs.
        BeginRecord();
        _run.StartRun();
        PrewarmBots();
        _spawnSeeds = new System.Random(seed != 0 ? unchecked(seed * 31 + 17) : System.Environment.TickCount);
        if (playerStats != null) playerStats.Bind(_run.Inventory);
        if (playerHealth != null)
        {
            playerHealth.SetAutoRespawn(false);
            playerHealth.ResetHealth();
        }
        SetHidden(true);
    }

    // Choice entry points for the run panels (R9) and debug keys (R11).
    public bool PickChestItem(int index)
    {
        if (Paused || _run.Phase != RunPhase.OpenChest || index < 0 || index >= _run.ChestChoices.Count) return false;
        string id = _run.ChestChoices[index].Id;
        if (!_run.Inventory.CanAdd(id)) return false;
        // Logged before the pick: picking can already start the next island (the boss).
        _recorder.ItemPicked(id, _run.Inventory.Level(id) + 1, ItemSource.Chest);
        return _run.PickChestItem(index);
    }

    public bool ChoosePortal(int index) => !Paused && _run.ChoosePortal(index);

    public bool BuyShopItem(int index)
    {
        Shop shop = _run.CurrentShop;
        string id = shop != null && index >= 0 && index < shop.Slots.Count ? shop.Slots[index].Item.Id : null;
        if (!_run.BuyShopItem(index)) return false;
        _recorder.ItemPicked(id, _run.Inventory.Level(id), ItemSource.Shop);
        return true;
    }

    public bool RerollShop()
    {
        if (!_run.RerollShop()) return false;
        _recorder.ShopRerolled();
        return true;
    }

    public bool LeaveShop() => !Paused && _run.LeaveShop();

    private bool Paused => match != null && match.IsPaused;

    private void Update()
    {
        if (debugKeys) HandleDebugKeys();
        if (!IsRunning)
        {
            // RUN button (after the tutorial on a first play): the match is in Run, the islands not yet.
            if (match == null || match.Match == null || match.Match.Phase != MatchPhase.Run) return;
            BeginRun();
        }

        // Back in the menu (MENU button, Esc, end screen): the run is over.
        if (match == null || match.Match.Phase != MatchPhase.Run)
        {
            EndRun();
            return;
        }

        SyncPause();
        _run.Params = rules;
        _run.Tick(Time.deltaTime);
        UpdateCorpses(Time.deltaTime);

        if (_run.Phase == RunPhase.Island && !_run.IsPaused) UpdateSpawning(Time.deltaTime);
        ApplyControls();
    }

    private void HandleDebugKeys()
    {
        Keyboard keyboard = Keyboard.current;
        if (keyboard == null) return;

        if (keyboard.rKey.wasPressedThisFrame && !IsRunning)
        {
            StartRun();
            return;
        }
        if (!IsRunning) return;

        int pick = keyboard.digit1Key.wasPressedThisFrame ? 0
            : keyboard.digit2Key.wasPressedThisFrame ? 1
            : keyboard.digit3Key.wasPressedThisFrame ? 2
            : -1;
        if (pick >= 0)
        {
            if (_run.Phase == RunPhase.OpenChest) PickChestItem(pick);
            else if (_run.Phase == RunPhase.ChoosePortal) ChoosePortal(pick);
        }
        else if (keyboard.bKey.wasPressedThisFrame && _run.Phase == RunPhase.Shop)
        {
            IReadOnlyList<ShopSlot> slots = _run.CurrentShop.Slots;
            for (int i = 0; i < slots.Count; i++)
                if (!slots[i].Sold && slots[i].Price <= _run.Crystals.Balance && BuyShopItem(i)) break;
        }
        else if (keyboard.nKey.wasPressedThisFrame)
        {
            LeaveShop();
        }
    }

    // The match owns pause (menus, focus loss, headset off); the run follows it.
    private void SyncPause()
    {
        if (match.IsPaused == _run.IsPaused) return;
        if (match.IsPaused) _run.Pause();
        else _run.Resume();
    }

    private void ApplyControls()
    {
        bool fighting = _run.Phase == RunPhase.Island && !_run.IsPaused;
        match.SetRunControls(fighting);
        for (int i = 0; i < _bots.Count; i++)
            if (_bots[i] != null) _bots[i].SetControlled(fighting);
    }

    private void UpdateSpawning(float dt)
    {
        if (_spawnTimer > 0f)
        {
            _spawnTimer -= dt;
            return;
        }
        while (_run.WantsSpawn(_bots.Count) && SpawnBot()) { }
    }

    private bool SpawnBot()
    {
        if (botPrefab == null || arena == null) return false;

        Vector3 at = arena.position;
        if (botSpawnPoints != null && botSpawnPoints.Length > 0)
        {
            Transform point = botSpawnPoints[_nextSpawnPoint++ % botSpawnPoints.Length];
            if (point != null) at = point.position;
        }

        PrewarmBots();
        RunBot bot = _botPool.Get();
        if (bot == null) return false; // every pooled bot busy: try again next frame

        int botSeed = BotBrain.SpawnSeed(_spawnSeeds ??= new System.Random(System.Environment.TickCount));
        bot.Activate(at, arena, playerHealth != null ? playerHealth.transform : null, _run.Spec, botSeed,
            _run.Phase == RunPhase.Island && !_run.IsPaused);
        _bots.Add(bot);
        return true;
    }

    // Scene load (Start), never mid-fight: MaxAlive + 1 bots, the extra one covers
    // a corpse still showing when the next bot spawns. The cap leaves room for
    // corpses of a whole wave. Later calls (run start, spawn) find the pool warm
    // and create nothing.
    private void PrewarmBots()
    {
        if (botPrefab == null || arena == null) return;
        int warm = Mathf.Max(1, rules.MaxAlive) + 1;
        if (_botPool == null)
            _botPool = new ObjectPool<RunBot>(CreateBot, warm * 2, null, ReleaseBot);
        _botPool.Prewarm(warm);
    }

    // GPU warmup (S1): one pooled bot for RenderWarmup to draw at scene load,
    // shown with RunBot.ShowForWarmup and handed back with ReturnWarmupBot. Null
    // while a run is on or when the pool has none free.
    public RunBot BorrowWarmupBot()
    {
        if (IsRunning) return null;
        PrewarmBots();
        return _botPool != null ? _botPool.Get() : null;
    }

    public void ReturnWarmupBot(RunBot bot)
    {
        if (_botPool != null) _botPool.Release(bot);
    }

    private RunBot CreateBot()
    {
        RunBot bot = Instantiate(botPrefab, arena.position, Quaternion.identity, arena);
        bot.Died += OnBotDied;
        return bot;
    }

    private static void ReleaseBot(RunBot bot)
    {
        if (bot != null) bot.Deactivate();
    }

    private void OnBotDied(RunBot bot)
    {
        if (!_bots.Remove(bot)) return;
        _spawnTimer = respawnInterval;
        _corpses.Add(bot);
        _corpseTimers.Add(corpseTime);
        _run.ReportBotKilled(); // may clear the island (despawns the rest)
    }

    // Game time, like the Destroy delay it replaces: a paused corpse waits.
    private void UpdateCorpses(float dt)
    {
        for (int i = _corpses.Count - 1; i >= 0; i--)
        {
            _corpseTimers[i] -= dt;
            if (_corpseTimers[i] > 0f) continue;
            _botPool.Release(_corpses[i]);
            _corpses.RemoveAt(i);
            _corpseTimers.RemoveAt(i);
        }
    }

    // Every death in a live run is resolved (BC-1): revive or Defeat. Auto
    // respawn is off, so an ignored death would leave the player dead.
    private void OnPlayerDied()
    {
        if (!IsRunning) return;
        // Logged first: a death without revives enters Defeat, which closes the record.
        if (!IsOver) _recorder.PlayerDied(revived: _run.RevivesLeft > 0);
        if (_run.ReportPlayerDeath()) playerHealth.Revive(_run.ReviveHealth(playerHealth.MaxHealth));
    }

    private void OnPlayerDamaged()
    {
        if (IsRunning && !IsOver) _recorder.DamageTaken(playerHealth.LastDamage);
    }

    private void OnRunPhaseChanged(RunPhase phase)
    {
        switch (phase)
        {
            case RunPhase.Intro:
                _recorder.IslandStarted(_run.Island, _run.Spec.Type);
                // Fresh island: the player back at the spawn point, health carried over.
                DespawnBots();
                _spawnTimer = 0f;
                if (playerHealth != null) playerHealth.ReturnToSpawn();
                break;

            case RunPhase.Island:
                _recorder.FightStarted(_run.RunTime);
                break;

            case RunPhase.IslandCleared:
                _recorder.FightEnded(_run.RunTime);
                DespawnBots();
                if (playerHealth != null && !playerHealth.IsDead)
                    playerHealth.SetHealth(_run.HealAfterClear(playerHealth.CurrentHealth, playerHealth.MaxHealth));
                break;

            case RunPhase.OpenChest:
                // Spiked chest: paid in health on opening, never lethal (Economy).
                if (_run.OpenedChest == ChestType.Spiked && playerHealth != null && !playerHealth.IsDead)
                    playerHealth.SetHealth(Economy.SpikedHealthAfter(playerHealth.CurrentHealth, playerHealth.MaxHealth));
                break;

            case RunPhase.Victory:
            case RunPhase.Defeat:
                DespawnBots();
                if (match != null) match.SetRunControls(false);
                FinishRecord(phase == RunPhase.Victory ? RunResult.Victory : RunResult.Defeat);
                break;
        }
    }

    private void BeginRecord()
    {
        string aim = aimModeSetting != null ? aimModeSetting.Mode.ToString() : "Unknown";
        string view = viewMode == null ? "Vr" : viewMode.IsTabletop ? "Table" : "Vr";
        _recorder.Begin(_rngSeed, aim, view, System.DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss"));
        if (playerAim == null) return;
        playerAim.ResetShotStats();
        playerAim.SetHoldRecording(true);
    }

    // Victory / Defeat (end screen) or quitting mid-run: never during a fight.
    // A second call for the same run does nothing.
    private void FinishRecord(RunResult result)
    {
        RunRecord record = _recorder.Finish(result, _run.RunTime, new RunTotals
        {
            Kills = _run.Kills,
            CrystalsEarned = _run.Crystals.TotalEarned,
            CrystalsSpent = _run.Crystals.TotalSpent,
            ShotsFired = playerAim != null ? playerAim.ShotsFired : 0,
            ShotsHit = playerAim != null ? playerAim.ShotsHit : 0,
            ChargeShots = playerAim != null ? playerAim.ChargeShotsFired : 0,
            Holds = playerAim != null ? playerAim.PinchHolds : null,
        });
        // The record copied the holds; menu and Quick Match pinches are not logged.
        if (playerAim != null) playerAim.SetHoldRecording(false);
        if (record != null && writeRunLog) RunLogFile.Append(RunRecordJson.ToJson(record));
    }

    private void EndRun()
    {
        if (_recorder.IsRecording) FinishRecord(RunResult.Quit);
        _run.ReturnToMenu();
        DespawnBots();
        if (playerStats != null) playerStats.Unbind();
        if (playerHealth != null)
        {
            playerHealth.SetAutoRespawn(true);
            playerHealth.ResetHealth();
        }
        SetHidden(false);
    }

    // Deactivate at once (BR-4a): despawned bots stop updating, lose their
    // colliders and leave the aim assist registry in this frame.
    private void DespawnBots()
    {
        if (_botPool != null) _botPool.ReleaseAll();
        _bots.Clear();
        _corpses.Clear();
        _corpseTimers.Clear();
    }

    private void SetHidden(bool hidden)
    {
        if (hideDuringRun == null) return;
        foreach (GameObject go in hideDuringRun)
            if (go != null && go.activeSelf == hidden) go.SetActive(!hidden);
    }
}
