using System.Collections.Generic;
using HandHero.Core;
using UnityEngine;
using UnityEngine.InputSystem;

// Runs RUN mode (autonomous plan R8) around RunStateMachine (HandHero.Core):
// spawns the island's bots from a prefab, scales them, counts kills, heals the
// player between islands and handles death / revive. MatchDirector stays the
// host: it owns pause, focus loss and the menu (MatchPhase.Run), so a run and
// a Quick Match can never be on at the same time. Nothing here moves the XR Origin.
public class RunDirector : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private MatchDirector match;
    [SerializeField] private HeroHealth playerHealth;
    [Tooltip("The player hero's run items; bound to the run's inventory while a run is on")]
    [SerializeField] private RunHeroStats playerStats;
    [Tooltip("Bot prefab generated by the scene builder (its own hero, input and controllers)")]
    [SerializeField] private RunBot botPrefab;
    [Tooltip("The arena root: spawned bots are parented here and use it for their bounds")]
    [SerializeField] private Transform arena;
    [Tooltip("Where bots appear, used in turn; empty = the arena center")]
    [SerializeField] private Transform[] botSpawnPoints;
    [Tooltip("Hidden while a run is on: the Quick Match bot hero and its ground marker")]
    [SerializeField] private GameObject[] hideDuringRun;

    [Header("Rules")]
    [SerializeField] private RunParams rules = RunParams.Default;
    [Tooltip("Seconds between a bot going down and the next one appearing (Horde, Arena 3)")]
    [SerializeField] private float respawnInterval = 1.5f;
    [Tooltip("Seconds a downed bot stays before it is removed (its last beam can finish)")]
    [SerializeField] private float corpseTime = 0.3f;
    [Tooltip("Random seed for chests, portals and the shop; 0 = different every run")]
    [SerializeField] private int seed;

    [Header("Debug keys (editor / desktop)")]
    [Tooltip("R = start a run (menu), 1-3 = pick a portal / chest card, B = buy the first affordable shop item, N = leave the shop")]
    [SerializeField] private bool debugKeys = true;

    private RunStateMachine _run;
    private readonly List<RunBot> _bots = new List<RunBot>();
    private float _spawnTimer;
    private int _nextSpawnPoint;

    public RunStateMachine Run => _run;
    public bool IsRunning => _run != null && _run.Phase != RunPhase.Idle;
    public int BotsAlive => _bots.Count;
    // VICTORY / DEFEAT showing; the run waits for MENU.
    public bool IsOver => _run != null && (_run.Phase == RunPhase.Victory || _run.Phase == RunPhase.Defeat);
    public HeroHealth PlayerHealth => playerHealth;

    private void Awake()
    {
        _run = new RunStateMachine(rules, new System.Random(seed != 0 ? seed : System.Environment.TickCount));
        _run.PhaseChanged += OnRunPhaseChanged;
    }

    private void OnEnable()
    {
        if (playerHealth != null) playerHealth.Died += OnPlayerDied;
    }

    private void OnDisable()
    {
        if (playerHealth != null) playerHealth.Died -= OnPlayerDied;
    }

    // Debug key entry point: straight into a run, no tutorial. Only from the main
    // menu. The RUN button goes through MatchDirector (tutorial first) instead;
    // Update begins the run once the match is in MatchPhase.Run.
    public bool StartRun()
    {
        if (IsRunning || match == null || !match.StartRun()) return false;
        BeginRun();
        return true;
    }

    private void BeginRun()
    {
        _run.Params = rules;
        _run.StartRun();
        if (playerStats != null) playerStats.Bind(_run.Inventory);
        if (playerHealth != null) playerHealth.ResetHealth();
        SetHidden(true);
    }

    // Choice entry points for the run panels (R9) and debug keys (R11).
    public bool PickChestItem(int index) => !Paused && _run.PickChestItem(index);
    public bool ChoosePortal(int index) => !Paused && _run.ChoosePortal(index);
    public bool BuyShopItem(int index) => _run.BuyShopItem(index);
    public bool RerollShop() => _run.RerollShop();
    public bool LeaveShop() => !Paused && _run.LeaveShop();

    private bool Paused => match != null && match.IsPaused;

    private void Update()
    {
        if (debugKeys) HandleDebugKeys();
        if (!IsRunning)
        {
            // RUN button (after the tutorial on a first play): the match is in Run, the islands not yet.
            if (match == null || match.Match == null || match.Match.Phase != MatchPhase.Run) return;
            BeginRun();
        }

        // Back in the menu (MENU button, Esc, end screen): the run is over.
        if (match == null || match.Match.Phase != MatchPhase.Run)
        {
            EndRun();
            return;
        }

        SyncPause();
        _run.Params = rules;
        _run.Tick(Time.deltaTime);

        if (_run.Phase == RunPhase.Island && !_run.IsPaused) UpdateSpawning(Time.deltaTime);
        ApplyControls();
    }

    private void HandleDebugKeys()
    {
        Keyboard keyboard = Keyboard.current;
        if (keyboard == null) return;

        if (keyboard.rKey.wasPressedThisFrame && !IsRunning)
        {
            StartRun();
            return;
        }
        if (!IsRunning) return;

        int pick = keyboard.digit1Key.wasPressedThisFrame ? 0
            : keyboard.digit2Key.wasPressedThisFrame ? 1
            : keyboard.digit3Key.wasPressedThisFrame ? 2
            : -1;
        if (pick >= 0)
        {
            if (_run.Phase == RunPhase.OpenChest) PickChestItem(pick);
            else if (_run.Phase == RunPhase.ChoosePortal) ChoosePortal(pick);
        }
        else if (keyboard.bKey.wasPressedThisFrame && _run.Phase == RunPhase.Shop)
        {
            IReadOnlyList<ShopSlot> slots = _run.CurrentShop.Slots;
            for (int i = 0; i < slots.Count; i++)
                if (!slots[i].Sold && slots[i].Price <= _run.Crystals.Balance && BuyShopItem(i)) break;
        }
        else if (keyboard.nKey.wasPressedThisFrame)
        {
            LeaveShop();
        }
    }

    // The match owns pause (menus, focus loss, headset off); the run follows it.
    private void SyncPause()
    {
        if (match.IsPaused == _run.IsPaused) return;
        if (match.IsPaused) _run.Pause();
        else _run.Resume();
    }

    private void ApplyControls()
    {
        bool fighting = _run.Phase == RunPhase.Island && !_run.IsPaused;
        match.SetRunControls(fighting);
        foreach (RunBot bot in _bots)
            if (bot != null) bot.SetControlled(fighting);
    }

    private void UpdateSpawning(float dt)
    {
        _bots.RemoveAll(b => b == null);
        if (_spawnTimer > 0f)
        {
            _spawnTimer -= dt;
            return;
        }
        while (_run.WantsSpawn(_bots.Count) && SpawnBot()) { }
    }

    private bool SpawnBot()
    {
        if (botPrefab == null || arena == null) return false;

        Vector3 at = arena.position;
        if (botSpawnPoints != null && botSpawnPoints.Length > 0)
        {
            Transform point = botSpawnPoints[_nextSpawnPoint++ % botSpawnPoints.Length];
            if (point != null) at = point.position;
        }

        RunBot bot = Instantiate(botPrefab, at, Quaternion.identity, arena);
        bot.Setup(arena, playerHealth != null ? playerHealth.transform : null, _run.Spec);
        bot.SetControlled(_run.Phase == RunPhase.Island && !_run.IsPaused);
        if (bot.Health != null) bot.Health.Died += () => OnBotDied(bot);
        _bots.Add(bot);
        return true;
    }

    private void OnBotDied(RunBot bot)
    {
        if (!_bots.Remove(bot)) return;
        _spawnTimer = respawnInterval;
        if (bot != null) Destroy(bot.gameObject, corpseTime);
        _run.ReportBotKilled(); // may clear the island (despawns the rest)
    }

    private void OnPlayerDied()
    {
        if (_run.Phase != RunPhase.Island) return;
        if (_run.ReportPlayerDeath()) playerHealth.Revive(_run.ReviveHealth(playerHealth.MaxHealth));
    }

    private void OnRunPhaseChanged(RunPhase phase)
    {
        switch (phase)
        {
            case RunPhase.Intro:
                // Fresh island: the player back at the spawn point, health carried over.
                DespawnBots();
                _spawnTimer = 0f;
                if (playerHealth != null) playerHealth.ReturnToSpawn();
                break;

            case RunPhase.IslandCleared:
                DespawnBots();
                if (playerHealth != null && !playerHealth.IsDead)
                    playerHealth.SetHealth(_run.HealAfterClear(playerHealth.CurrentHealth, playerHealth.MaxHealth));
                break;

            case RunPhase.OpenChest:
                // Spiked chest: paid in health on opening, never lethal (Economy).
                if (_run.OpenedChest == ChestType.Spiked && playerHealth != null && !playerHealth.IsDead)
                    playerHealth.SetHealth(Economy.SpikedHealthAfter(playerHealth.CurrentHealth, playerHealth.MaxHealth));
                break;

            case RunPhase.Victory:
            case RunPhase.Defeat:
                DespawnBots();
                if (match != null) match.SetRunControls(false);
                break;
        }
    }

    private void EndRun()
    {
        _run.ReturnToMenu();
        DespawnBots();
        if (playerStats != null) playerStats.Unbind();
        if (playerHealth != null) playerHealth.ResetHealth();
        SetHidden(false);
    }

    private void DespawnBots()
    {
        foreach (RunBot bot in _bots)
            if (bot != null) Destroy(bot.gameObject);
        _bots.Clear();
    }

    private void SetHidden(bool hidden)
    {
        if (hideDuringRun == null) return;
        foreach (GameObject go in hideDuringRun)
            if (go != null && go.activeSelf == hidden) go.SetActive(!hidden);
    }
}
